### ISSUE TITLE
[Solved] Build error with latest toolchain...

### ISSUE THREAD

**Issue by dl9sec** [mogenson/flipperzero-waveshare-nfc#1]
Hi,

yesterday I followed all the instruction how to setup this Rust stuff and tried to build "flipperzero-waveshare-nfc" with "cargo build".
Unfortunately I got the following error:

```
error[E0635]: unknown feature `proc_macro_span_shrink`
  --> C:\Users\thors\.cargo\registry\src\index.crates.io-6f17d22bba15001f\proc-macro2-1.0.59\src\lib.rs:92:30
   |
92 |     feature(proc_macro_span, proc_macro_span_shrink)
   |                              ^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0635`.
error: could not compile `proc-macro2` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
```

I solved this by updating the "proc-macro2" dependency with:

`cargo update -p proc-macro2 --precise 1.0.60`

A 
`cargo fix --bin "flipper-nfc-waveshare"`
respectively
`cargo fix --allow-dirty --bin "flipper-nfc-waveshare"` (for a quick'n'dirty build without committing something)

fixed a last warning:

```
warning: unused import: `print`
  --> src\main.rs:16:19
   |
16 | use flipperzero::{print, println};
   |                   ^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: `flipper-nfc-waveshare` (bin "flipper-nfc-waveshare") generated 1 warning (run `cargo fix --bin "flipper-nfc-waveshare"` to apply 1 suggestion)
```

The app works like a charm for my 4.2" Waveshare frame. Great stuff! Thanks :-)

Regards, Thorsten

**Comment by mogenson** [comment]
Thanks for identifying the fix? Would you be willing to put up a PR? Maybe we should pin the toolchain to a specific nightly version.

**Comment by dl9sec** [comment]
PR done...
