### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by dl9sec** [mogenson/flipperzero-waveshare-nfc#3]
Hi Michael,

would be great if the project gets a license/license text to know what it is allowed to do with the sources...

Regards, Thorsten

**Comment by mogenson** [comment]
I'll add one. My preference is MIT, unless there's a reason why that wouldn't work for your needs.

**Comment by dl9sec** [comment]
MIT (as the most popular permissive license at Giuhub) is great and would have been my choice and suggestion too.
Thank you.

**Comment by mogenson** [comment]
Closed with 77058db
